# Dependencies
markdown:         kramdown

# redcarpet:
#   extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables"]

#highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Daniel Taveras
tagline:          'web developer'
description:      'Coder, technician, and console cowboy'
url:              https://www.danieltaveras.com

author:
  name:           'Daniel Taveras'
  url:            https://www.danieltaveras.com


# Custom vars
version:          2.0.0

github:           taveras
twitter:          danieljtaveras
linkedin:         taveras
keybase:          taveras

sass:
  sass_dir:       _sass
  style:          compressed

