# Dependencies
markdown:         redcarpet

redcarpet:
  extensions: ["no_intra_emphasis", "fenced_code_blocks", "autolink", "tables"]

highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Daniel Taveras
tagline:          'web developer'
description:      'Coder, technician, console cowboy, technocrat!'
url:              http://danieltaveras.com

author:
  name:           'Daniel Taveras'
  url:            http://danieltaveras.com

paginate:         5

# Custom vars
version:          2.0.0

github:           taveras
twitter:          danieljtaveras
linkedin:         danieltaveras

sass:
  sass_dir: _sass
  style: compressed